# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '0008_auto_20161017_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='MaterialsRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, verbose_name='Material Name')),
                ('material_code', models.CharField(max_length=25, unique=True)),
                ('quantity_required', models.PositiveIntegerField(verbose_name='Qty Issued (kg)')),
                ('quantity_issued', models.PositiveIntegerField(verbose_name='Qty Required (kg)')),
                ('ar_no', models.CharField(max_length=25, unique=True, verbose_name='A.R No')),
                ('batch_no', models.CharField(blank=True, max_length=25, unique=True)),
            ],
            options={
                'ordering': ('material',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=25, unique=True)),
                ('batch_size', models.PositiveIntegerField(blank=True, verbose_name='Batch Size (kg)')),
                ('manufacture_date', models.DateField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('batch_no', 'name'),
            },
        ),
        migrations.AddField(
            model_name='materialsrequired',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_dept.Product'),
        ),
        migrations.CreateModel(
            name='GoodsTransferNote',
            fields=[
            ],
            options={
                'ordering': ('batch_no',),
                'proxy': True,
                'indexes': [],
            },
            bases=('production_dept.product',),
        ),
    ]
