# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=50, unique=True)),
                ('dept_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ('dept_num',),
            },
        ),
        migrations.CreateModel(
            name='DepartmentManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('department', models.ForeignKey(db_column='dept_num', on_delete=django.db.models.deletion.CASCADE, to='staff.Department')),
            ],
            options={
                'verbose_name_plural': 'Department Managers',
                'db_table': 'dept_manager',
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('department', models.ForeignKey(db_column='dept_num', on_delete=django.db.models.deletion.CASCADE, to='staff.Department')),
            ],
            options={
                'verbose_name_plural': 'Department Staff',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_num', models.IntegerField(primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=1)),
                ('hire_date', models.DateField()),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee', models.ForeignKey(db_column='emp_num', on_delete=django.db.models.deletion.CASCADE, to='staff.Employee')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salaries',
                'db_table': 'salaries',
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='emp_num', on_delete=django.db.models.deletion.CASCADE, to='staff.Employee')),
            ],
            options={
                'db_table': 'titles',
            },
        ),
        migrations.AddField(
            model_name='departmentstaff',
            name='employee',
            field=models.ForeignKey(db_column='emp_num', on_delete=django.db.models.deletion.CASCADE, to='staff.Employee'),
        ),
        migrations.AddField(
            model_name='departmentmanager',
            name='employee',
            field=models.ForeignKey(db_column='emp_num', on_delete=django.db.models.deletion.CASCADE, to='staff.Employee'),
        ),
    ]
