# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '0008_auto_20161017_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_num', models.CharField(default=uuid.uuid4, editable=False, max_length=10, verbose_name='Ticket Number')),
                ('description', models.TextField()),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
            ],
        ),
    ]
